version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: dependencies install
          command: npm install
      - run:
          name: build create
          command: npm run build
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            scp -v -o StrictHostKeyChecking=no -r build $SSH_USER@$SSH_HOST:/test/build-data
# ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
# scp -v -o StrictHostKeyChecking=no -r build $SSH_USER@$SSH_HOST:/test/build-data
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
