version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: dependencies install
          command: npm install
      - run:
          name: build create
          command: npm run build

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: fix host authenticity for production server
          command: |
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "ca:7d:ee:a7:80:d9:1a:46:f5:a7:bd:37:f9:ad:65:7c"
      # - run:
      #     name: Test SSH echo(1)
      #     command: |
      #       ssh -v -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST
      #       "echo TEST#1 CircleCI | exit"
      # - run:
      #     name: Test SSH echo(2 without)
      #     command: |
      #       ssh -v $SSH_USER@$SSH_HOST
      #       "echo TEST#2 CircleCI | exit"
      # - run:
      #     name: Deploy Over SSH
      #     command: |
      #       scp -v ~/app/* -r build $SSH_USER@$SSH_HOST:/home/test/build-test
      # - run:
      #     name: Deploy Over SSH (2)
      #     command: |
      #       scp -v -r app $SSH_USER@$SSH_HOST:/home/test/build-test
      - run:
          name: Deploy Over SSH (2)
          command: |
            scp -v -r ./* $SSH_USER@$SSH_HOST:/home/test/build-test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
