version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: dependencies install
          command: npm install
      - run:
          name: build create
          command: npm run build

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: fix host authenticity for production server
          command: |
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "89:62:d2:4a:de:3f:75:da:21:81:45:95:9d:2c:ab:a9"
      # - run:
      #     name: Test SSH echo(1)
      #     command: |
      #       ssh -v -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST
      #       "echo TEST#1 CircleCI | exit"
      # - run:
      #     name: Test SSH echo(2 without)
      #     command: |
      #       ssh -v $SSH_USER@$SSH_HOST
      #       "echo TEST#2 CircleCI | exit"
      - run:
          name: Deploy Over SSH
          command: |
            scp -v ~/app/* -r build $SSH_USER@$SSH_HOST:/home/test/build-test
      - run:
          name: Deploy Over SSH (2)
          command: |
            scp -v ~/project -r build $SSH_USER@$SSH_HOST:/home/test/build-test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
