version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: dependencies install
          command: npm install
      - run:
          name: build create
          command: npm run build
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "89:62:d2:4a:de:3f:75:da:21:81:45:95:9d:2c:ab:a9"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            scp -v -o StrictHostKeyChecking=no -r build $SSH_USER@$SSH_HOST:/home/test/build-test
# ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
# scp -v -o StrictHostKeyChecking=no -r build $SSH_USER@$SSH_HOST:/test/build-data
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
